/*
 * VestaVM - Maquina Virtual Distribuida
 *
 * Copyright (C) 2026 David Lopez.T (DesmonHak) (Castilla y Leon, ES)
 * Licencia: GPLv2 + excepcion de runtime (ver LICENSE).
 *
 * Software libre bajo GPLv2.  La salida del compilador (programas
 * escritos en Vesta) NO queda sujeta a la GPL (excepcion de runtime).
 */

/**
 * @file emmit/instr_list.h
 * @brief La lista de instrucciones del `.vel`.  UNA vez, aqui.
 *
 * De aqui salen el enum de mnemonicos y, cuando se migren, las tablas del parser
 * y del emisor de bytecode.  Se incluye definiendo @c VX_INSTR y cada consumidor
 * decide que hacer con cada linea; no lleva guarda de inclusion a proposito,
 * porque se incluye VARIAS veces con macros distintas.
 *
 * ## Por que existe
 *
 * La lista vivia DOS veces -- `InstrSet` en el parser e `InstrTable` en el
 * emisor --, las dos indexadas por cadena, y ya habian divergido: cinco
 * instrucciones estaban en la del emisor y el parser no las conocia, con lo que
 * eran INALCANZABLES (nadie podia escribirlas en un `.vel`).  Tres de ellas son
 * legacy a la espera de retirarse; `callnr` y `jmpr` no tienen esa excusa.
 *
 * Con la lista aqui, anadir una instruccion a medias no compila.
 *
 * ## Como se usa
 *
 * @code
 * #define VX_INSTR(id, texto) id,
 * enum class Mnemonico { VX_INSTR_LISTA };
 * #undef VX_INSTR
 * @endcode
 *
 * Cada identificador lleva prefijo `i_` y el punto sustituido por `_`
 * (`jmp.je` -> `i_jmp_je`).  El prefijo es UNIFORME y no solo donde hace falta:
 * `and`, `or`, `xor` y `not` son tokens alternativos de C++ y no valen como
 * identificadores, y una lista de excepciones seria otra cosa que mantener.  El
 * texto real del mnemonico va como segundo campo.
 */

/* clang-format off */
VX_INSTR(i_addadvice, "addadvice")
VX_INSTR(i_addcur, "addcur")
VX_INSTR(i_adds, "adds")
VX_INSTR(i_adds3, "adds3")
VX_INSTR(i_addsp, "addsp")
VX_INSTR(i_addu, "addu")
VX_INSTR(i_addu3, "addu3")
VX_INSTR(i_alloc, "alloc")
VX_INSTR(i_and, "and")
VX_INSTR(i_and3, "and3")
VX_INSTR(i_atomicadd, "atomicadd")
VX_INSTR(i_atomiccas, "atomiccas")
VX_INSTR(i_atomicld, "atomicld")
VX_INSTR(i_atomicst, "atomicst")
VX_INSTR(i_await, "await")
VX_INSTR(i_bitg2z, "bitg2z")
VX_INSTR(i_bitz2g, "bitz2g")
VX_INSTR(i_callclosure, "callclosure")
VX_INSTR(i_callitf, "callitf")
VX_INSTR(i_callm, "callm")
VX_INSTR(i_calln, "calln")
VX_INSTR(i_callni, "callni")
VX_INSTR(i_callnr, "callnr")
VX_INSTR(i_callrawclosure, "callrawclosure")
VX_INSTR(i_callsuper, "callsuper")
VX_INSTR(i_callvirt, "callvirt")
VX_INSTR(i_callvm, "callvm")
VX_INSTR(i_callvmr, "callvmr")
VX_INSTR(i_checkcast, "checkcast")
VX_INSTR(i_classattrcount, "classattrcount")
VX_INSTR(i_classattrkey, "classattrkey")
VX_INSTR(i_classattrval, "classattrval")
VX_INSTR(i_classdoc, "classdoc")
VX_INSTR(i_classname, "classname")
VX_INSTR(i_cmpjmp_jae, "cmpjmp.jae")
VX_INSTR(i_cmpjmp_jb, "cmpjmp.jb")
VX_INSTR(i_cmpjmp_jcc, "cmpjmp.jcc")
VX_INSTR(i_cmpjmp_jcs, "cmpjmp.jcs")
VX_INSTR(i_cmpjmp_je, "cmpjmp.je")
VX_INSTR(i_cmpjmp_jge, "cmpjmp.jge")
VX_INSTR(i_cmpjmp_jgt, "cmpjmp.jgt")
VX_INSTR(i_cmpjmp_jhi, "cmpjmp.jhi")
VX_INSTR(i_cmpjmp_jle, "cmpjmp.jle")
VX_INSTR(i_cmpjmp_jls, "cmpjmp.jls")
VX_INSTR(i_cmpjmp_jlt, "cmpjmp.jlt")
VX_INSTR(i_cmpjmp_jmi, "cmpjmp.jmi")
VX_INSTR(i_cmpjmp_jne, "cmpjmp.jne")
VX_INSTR(i_cmpjmp_jnz, "cmpjmp.jnz")
VX_INSTR(i_cmpjmp_jpl, "cmpjmp.jpl")
VX_INSTR(i_cmpjmp_jvc, "cmpjmp.jvc")
VX_INSTR(i_cmpjmp_jvs, "cmpjmp.jvs")
VX_INSTR(i_cmpjmp_jz, "cmpjmp.jz")
VX_INSTR(i_cmpjmpu_jae, "cmpjmpu.jae")
VX_INSTR(i_cmpjmpu_jb, "cmpjmpu.jb")
VX_INSTR(i_cmpjmpu_jcc, "cmpjmpu.jcc")
VX_INSTR(i_cmpjmpu_jcs, "cmpjmpu.jcs")
VX_INSTR(i_cmpjmpu_je, "cmpjmpu.je")
VX_INSTR(i_cmpjmpu_jge, "cmpjmpu.jge")
VX_INSTR(i_cmpjmpu_jgt, "cmpjmpu.jgt")
VX_INSTR(i_cmpjmpu_jhi, "cmpjmpu.jhi")
VX_INSTR(i_cmpjmpu_jle, "cmpjmpu.jle")
VX_INSTR(i_cmpjmpu_jls, "cmpjmpu.jls")
VX_INSTR(i_cmpjmpu_jlt, "cmpjmpu.jlt")
VX_INSTR(i_cmpjmpu_jmi, "cmpjmpu.jmi")
VX_INSTR(i_cmpjmpu_jne, "cmpjmpu.jne")
VX_INSTR(i_cmpjmpu_jnz, "cmpjmpu.jnz")
VX_INSTR(i_cmpjmpu_jpl, "cmpjmpu.jpl")
VX_INSTR(i_cmpjmpu_jvc, "cmpjmpu.jvc")
VX_INSTR(i_cmpjmpu_jvs, "cmpjmpu.jvs")
VX_INSTR(i_cmpjmpu_jz, "cmpjmpu.jz")
VX_INSTR(i_cmps, "cmps")
VX_INSTR(i_cmpu, "cmpu")
VX_INSTR(i_csel, "csel")
VX_INSTR(i_dec, "dec")
VX_INSTR(i_decjnz, "decjnz")
VX_INSTR(i_defclass, "defclass")
VX_INSTR(i_deffield, "deffield")
VX_INSTR(i_defmethod, "defmethod")
VX_INSTR(i_deref_weak, "deref_weak")
VX_INSTR(i_divs, "divs")
VX_INSTR(i_divu, "divu")
VX_INSTR(i_dlopen, "dlopen")
VX_INSTR(i_dlsym, "dlsym")
VX_INSTR(i_drop, "drop")
VX_INSTR(i_edm, "edm")
VX_INSTR(i_edmw4, "edmw4")
VX_INSTR(i_edmw6, "edmw6")
VX_INSTR(i_enter, "enter")
VX_INSTR(i_fabs, "fabs")
VX_INSTR(i_fabs_pd, "fabs.pd")
VX_INSTR(i_fabs_ps, "fabs.ps")
VX_INSTR(i_fadd, "fadd")
VX_INSTR(i_fadd_pd, "fadd.pd")
VX_INSTR(i_fadd_ps, "fadd.ps")
VX_INSTR(i_fastpop, "fastpop")
VX_INSTR(i_fastpush, "fastpush")
VX_INSTR(i_fceil, "fceil")
VX_INSTR(i_fceil_ps, "fceil.ps")
VX_INSTR(i_fcmp, "fcmp")
VX_INSTR(i_fcmp_pd, "fcmp.pd")
VX_INSTR(i_fcmp_ps, "fcmp.ps")
VX_INSTR(i_fcvt, "fcvt")
VX_INSTR(i_fcvt_ps, "fcvt.ps")
VX_INSTR(i_fdiv, "fdiv")
VX_INSTR(i_fdiv_pd, "fdiv.pd")
VX_INSTR(i_fdiv_ps, "fdiv.ps")
VX_INSTR(i_fextend, "fextend")
VX_INSTR(i_ffloor, "ffloor")
VX_INSTR(i_ffloor_ps, "ffloor.ps")
VX_INSTR(i_fieldattrcount, "fieldattrcount")
VX_INSTR(i_fieldattrkey, "fieldattrkey")
VX_INSTR(i_fieldattrval, "fieldattrval")
VX_INSTR(i_fieldcount, "fieldcount")
VX_INSTR(i_fielddoc, "fielddoc")
VX_INSTR(i_fieldname, "fieldname")
VX_INSTR(i_findclass, "findclass")
VX_INSTR(i_findfield, "findfield")
VX_INSTR(i_findmethod, "findmethod")
VX_INSTR(i_fload, "fload")
VX_INSTR(i_fmadd, "fmadd")
VX_INSTR(i_fmadd_ps, "fmadd.ps")
VX_INSTR(i_fmax, "fmax")
VX_INSTR(i_fmax_ps, "fmax.ps")
VX_INSTR(i_fmin, "fmin")
VX_INSTR(i_fmin_ps, "fmin.ps")
VX_INSTR(i_fmov, "fmov")
VX_INSTR(i_fmowi, "fmowi")
VX_INSTR(i_fmul, "fmul")
VX_INSTR(i_fmul_pd, "fmul.pd")
VX_INSTR(i_fmul_ps, "fmul.ps")
VX_INSTR(i_fnarrow, "fnarrow")
VX_INSTR(i_fneg, "fneg")
VX_INSTR(i_fneg_pd, "fneg.pd")
VX_INSTR(i_fneg_ps, "fneg.ps")
VX_INSTR(i_free, "free")
VX_INSTR(i_free_weak, "free_weak")
VX_INSTR(i_fround, "fround")
VX_INSTR(i_fround_ps, "fround.ps")
VX_INSTR(i_fsqrt, "fsqrt")
VX_INSTR(i_fsqrt_pd, "fsqrt.pd")
VX_INSTR(i_fsqrt_ps, "fsqrt.ps")
VX_INSTR(i_fstore, "fstore")
VX_INSTR(i_fsub, "fsub")
VX_INSTR(i_fsub_pd, "fsub.pd")
VX_INSTR(i_fsub_ps, "fsub.ps")
VX_INSTR(i_ftrunc, "ftrunc")
VX_INSTR(i_ftrunc_ps, "ftrunc.ps")
VX_INSTR(i_fulfill, "fulfill")
VX_INSTR(i_fulfillhlt, "fulfillhlt")
VX_INSTR(i_future, "future")
VX_INSTR(i_gcalloc, "gcalloc")
VX_INSTR(i_gcallocp, "gcallocp")
VX_INSTR(i_gccollect, "gccollect")
VX_INSTR(i_gcconfig, "gcconfig")
VX_INSTR(i_gcdemote, "gcdemote")
VX_INSTR(i_gcderef, "gcderef")
VX_INSTR(i_gcfinal, "gcfinal")
VX_INSTR(i_gcfinalc, "gcfinalc")
VX_INSTR(i_gcfinall, "gcfinall")
VX_INSTR(i_gchandle, "gchandle")
VX_INSTR(i_gcpromote, "gcpromote")
VX_INSTR(i_gcrun, "gcrun")
VX_INSTR(i_gcwb, "gcwb")
VX_INSTR(i_getarg, "getarg")
VX_INSTR(i_getargc, "getargc")
VX_INSTR(i_getclass, "getclass")
VX_INSTR(i_getfield, "getfield")
VX_INSTR(i_getfldat, "getfldat")
VX_INSTR(i_getmethat, "getmethat")
VX_INSTR(i_getmethod, "getmethod")
VX_INSTR(i_getmgr, "getmgr")
VX_INSTR(i_getpid, "getpid")
VX_INSTR(i_getproc, "getproc")
VX_INSTR(i_getstatic, "getstatic")
VX_INSTR(i_getvm, "getvm")
VX_INSTR(i_hlt, "hlt")
VX_INSTR(i_htrack, "htrack")
VX_INSTR(i_inc, "inc")
VX_INSTR(i_instanceof, "instanceof")
VX_INSTR(i_isnull, "isnull")
VX_INSTR(i_jmp, "jmp")
VX_INSTR(i_jmp_jae, "jmp.jae")
VX_INSTR(i_jmp_jb, "jmp.jb")
VX_INSTR(i_jmp_jcc, "jmp.jcc")
VX_INSTR(i_jmp_jcs, "jmp.jcs")
VX_INSTR(i_jmp_je, "jmp.je")
VX_INSTR(i_jmp_jge, "jmp.jge")
VX_INSTR(i_jmp_jgt, "jmp.jgt")
VX_INSTR(i_jmp_jhi, "jmp.jhi")
VX_INSTR(i_jmp_jle, "jmp.jle")
VX_INSTR(i_jmp_jls, "jmp.jls")
VX_INSTR(i_jmp_jlt, "jmp.jlt")
VX_INSTR(i_jmp_jmi, "jmp.jmi")
VX_INSTR(i_jmp_jne, "jmp.jne")
VX_INSTR(i_jmp_jnz, "jmp.jnz")
VX_INSTR(i_jmp_jpl, "jmp.jpl")
VX_INSTR(i_jmp_jvc, "jmp.jvc")
VX_INSTR(i_jmp_jvs, "jmp.jvs")
VX_INSTR(i_jmp_jz, "jmp.jz")
VX_INSTR(i_jmpr, "jmpr")
VX_INSTR(i_jrel, "jrel")
VX_INSTR(i_jrel_jae, "jrel.jae")
VX_INSTR(i_jrel_jb, "jrel.jb")
VX_INSTR(i_jrel_jcc, "jrel.jcc")
VX_INSTR(i_jrel_jcs, "jrel.jcs")
VX_INSTR(i_jrel_je, "jrel.je")
VX_INSTR(i_jrel_jge, "jrel.jge")
VX_INSTR(i_jrel_jgt, "jrel.jgt")
VX_INSTR(i_jrel_jhi, "jrel.jhi")
VX_INSTR(i_jrel_jle, "jrel.jle")
VX_INSTR(i_jrel_jls, "jrel.jls")
VX_INSTR(i_jrel_jlt, "jrel.jlt")
VX_INSTR(i_jrel_jmi, "jrel.jmi")
VX_INSTR(i_jrel_jne, "jrel.jne")
VX_INSTR(i_jrel_jnz, "jrel.jnz")
VX_INSTR(i_jrel_jpl, "jrel.jpl")
VX_INSTR(i_jrel_jvc, "jrel.jvc")
VX_INSTR(i_jrel_jvs, "jrel.jvs")
VX_INSTR(i_jrel_jz, "jrel.jz")
VX_INSTR(i_jumptable, "jumptable")
VX_INSTR(i_leave, "leave")
VX_INSTR(i_loadmod, "loadmod")
VX_INSTR(i_loadz, "loadz")
VX_INSTR(i_loadzh, "loadzh")
VX_INSTR(i_loop, "loop")
VX_INSTR(i_memcpy, "memcpy")
VX_INSTR(i_memcpyh, "memcpyh")
VX_INSTR(i_memset, "memset")
VX_INSTR(i_memseth, "memseth")
VX_INSTR(i_memsync, "memsync")
VX_INSTR(i_methodattrcount, "methodattrcount")
VX_INSTR(i_methodattrkey, "methodattrkey")
VX_INSTR(i_methodattrval, "methodattrval")
VX_INSTR(i_methodcount, "methodcount")
VX_INSTR(i_methoddesc, "methoddesc")
VX_INSTR(i_methoddoc, "methoddoc")
VX_INSTR(i_methodname, "methodname")
VX_INSTR(i_mkclosure, "mkclosure")
VX_INSTR(i_mkrawclosure, "mkrawclosure")
VX_INSTR(i_mld, "mld")
VX_INSTR(i_mods, "mods")
VX_INSTR(i_modu, "modu")
VX_INSTR(i_monenter, "monenter")
VX_INSTR(i_monexit, "monexit")
VX_INSTR(i_monnota, "monnota")
VX_INSTR(i_monnoti, "monnoti")
VX_INSTR(i_monwait, "monwait")
VX_INSTR(i_mov, "mov")
VX_INSTR(i_movc, "movc")
VX_INSTR(i_movch, "movch")
VX_INSTR(i_movh, "movh")
VX_INSTR(i_msgrecv, "msgrecv")
VX_INSTR(i_msgsend, "msgsend")
VX_INSTR(i_mst, "mst")
VX_INSTR(i_muls, "muls")
VX_INSTR(i_muls3, "muls3")
VX_INSTR(i_mulu, "mulu")
VX_INSTR(i_mulu3, "mulu3")
VX_INSTR(i_mvtake, "mvtake")
VX_INSTR(i_newobj, "newobj")
VX_INSTR(i_newobjraw, "newobjraw")
VX_INSTR(i_newobjs, "newobjs")
VX_INSTR(i_nop1, "nop1")
VX_INSTR(i_nop2, "nop2")
VX_INSTR(i_not, "not")
VX_INSTR(i_or, "or")
VX_INSTR(i_or3, "or3")
VX_INSTR(i_panic, "panic")
VX_INSTR(i_pop, "pop")
VX_INSTR(i_proceed, "proceed")
VX_INSTR(i_push, "push")
VX_INSTR(i_readcur, "readcur")
VX_INSTR(i_realloc, "realloc")
VX_INSTR(i_reject, "reject")
VX_INSTR(i_resume, "resume")
VX_INSTR(i_ret, "ret")
VX_INSTR(i_rethrow, "rethrow")
VX_INSTR(i_rspawn, "rspawn")
VX_INSTR(i_sar, "sar")
VX_INSTR(i_setcc, "setcc")
VX_INSTR(i_setmethdbg, "setmethdbg")
VX_INSTR(i_setstatic, "setstatic")
VX_INSTR(i_sext, "sext")
VX_INSTR(i_sharedstat, "sharedstat")
VX_INSTR(i_shl, "shl")
VX_INSTR(i_shr, "shr")
VX_INSTR(i_spawn, "spawn")
VX_INSTR(i_spawnargs, "spawnargs")
VX_INSTR(i_spawnon, "spawnon")
VX_INSTR(i_specialize, "specialize")
VX_INSTR(i_strcat, "strcat")
VX_INSTR(i_strcmp, "strcmp")
VX_INSTR(i_strconv, "strconv")
VX_INSTR(i_strfinalize, "strfinalize")
VX_INSTR(i_strflat, "strflat")
VX_INSTR(i_strgetbytes, "strgetbytes")
VX_INSTR(i_strgetenc, "strgetenc")
VX_INSTR(i_strgetkind, "strgetkind")
VX_INSTR(i_strhash, "strhash")
VX_INSTR(i_strintern, "strintern")
VX_INSTR(i_strlen, "strlen")
VX_INSTR(i_strmake, "strmake")
VX_INSTR(i_strmake_h, "strmake_h")
VX_INSTR(i_strraw, "strraw")
VX_INSTR(i_strreserve, "strreserve")
VX_INSTR(i_strslice, "strslice")
VX_INSTR(i_subs, "subs")
VX_INSTR(i_subs3, "subs3")
VX_INSTR(i_subsp, "subsp")
VX_INSTR(i_subu, "subu")
VX_INSTR(i_subu3, "subu3")
VX_INSTR(i_swapctx, "swapctx")
VX_INSTR(i_tailcall, "tailcall")
VX_INSTR(i_throw, "throw")
VX_INSTR(i_tryenter, "tryenter")
VX_INSTR(i_tryleave, "tryleave")
VX_INSTR(i_typeswitch, "typeswitch")
VX_INSTR(i_unloadmod, "unloadmod")
VX_INSTR(i_unwrap, "unwrap")
VX_INSTR(i_vcopyh, "vcopyh")
VX_INSTR(i_vmcopy, "vmcopy")
VX_INSTR(i_vminfo, "vminfo")
VX_INSTR(i_vminfomanager, "vminfomanager")
VX_INSTR(i_weakref, "weakref")
VX_INSTR(i_writecur, "writecur")
VX_INSTR(i_xchg, "xchg")
VX_INSTR(i_xor, "xor")
VX_INSTR(i_xor3, "xor3")
VX_INSTR(i_yield, "yield")
/* clang-format on */
