/*
 * VestaVM - Maquina Virtual Distribuida
 *
 * Copyright (C) 2026 David Lopez.T (DesmonHak) (Castilla y Leon, ES)
 * Licencia: GPLv2 + excepcion de runtime (ver LICENSE).
 *
 * Software libre bajo GPLv2.  La salida del compilador (programas
 * escritos en Vesta) NO queda sujeta a la GPL (excepcion de runtime).
 */

/**
 * @file emmit/instr_list.h
 * @brief Las instrucciones del `.vel`, UNA vez y agrupadas por lo que hacen.
 *
 * De aqui salen el enum de mnemonicos, sus nombres y su categoria; y cuando se
 * migren, las tablas del parser y del emisor de bytecode.  Se incluye
 * definiendo
 * @c VX_INSTR y cada consumidor decide que hacer con cada linea.  No lleva
 * guarda de inclusion a proposito: se incluye varias veces con macros
 * distintas.
 *
 * ## Por que existe
 *
 * La lista vivia DOS veces -- `InstrSet` (parser) e `InstrTable` (emisor) --,
 * las dos indexadas por cadena, y ya habian divergido: `callnr` y `jmpr` estan
 * en la del emisor y el parser no las conoce, con lo que son INALCANZABLES. Eso
 * no da error: da una instruccion que parece existir y no se puede usar.
 *
 * ## El ORDEN no es alfabetico, es por categoria
 *
 * Va agrupado para que cada categoria sea un rango CONTIGUO.  Asi preguntar si
 * una instruccion es un salto, o una llamada, son dos comparaciones -- sin
 * tabla que consultar ni salto que predecir.  Alfabetico obligaria a mirar una
 * tabla para cada pregunta de ese tipo, y esas preguntas se hacen en bucles
 * calientes: el clasificador de terminadores del asm, el planificador, el
 * analisis de efectos.
 *
 * La categoria sale de las SECCIONES en las que ya estaba dividida la tabla del
 * emisor -- no se invento aqui.
 *
 * ## Nombres
 *
 * En mayusculas y sin prefijo: `CALLVIRT` se lee, `i_callvirt` no.  Y en
 * mayusculas tampoco chocan con `and`/`or`/`xor`/`not`, que son tokens
 * alternativos de C++ solo en minuscula.  El punto se sustituye por `_`
 * (`jmp.je` -> `JMP_JE`) porque un identificador no lo admite; el texto real va
 * como segundo campo.
 */

/* --- Arithmetic --- */
VX_INSTR(ADDS, "adds", Arithmetic)
VX_INSTR(ADDS3, "adds3", Arithmetic)
VX_INSTR(ADDU, "addu", Arithmetic)
VX_INSTR(ADDU3, "addu3", Arithmetic)
VX_INSTR(AND3, "and3", Arithmetic)
VX_INSTR(DIVS, "divs", Arithmetic)
VX_INSTR(DIVU, "divu", Arithmetic)
VX_INSTR(MEMCPY, "memcpy", Arithmetic)
VX_INSTR(MEMCPYH, "memcpyh", Arithmetic)
VX_INSTR(MEMSET, "memset", Arithmetic)
VX_INSTR(MEMSETH, "memseth", Arithmetic)
VX_INSTR(MODS, "mods", Arithmetic)
VX_INSTR(MODU, "modu", Arithmetic)
VX_INSTR(MULS, "muls", Arithmetic)
VX_INSTR(MULS3, "muls3", Arithmetic)
VX_INSTR(MULU, "mulu", Arithmetic)
VX_INSTR(MULU3, "mulu3", Arithmetic)
VX_INSTR(OR3, "or3", Arithmetic)
VX_INSTR(SUBS, "subs", Arithmetic)
VX_INSTR(SUBS3, "subs3", Arithmetic)
VX_INSTR(SUBU, "subu", Arithmetic)
VX_INSTR(SUBU3, "subu3", Arithmetic)
VX_INSTR(XOR3, "xor3", Arithmetic)

/* --- Bitwise --- */
VX_INSTR(AND, "and", Bitwise)
VX_INSTR(CALLN, "calln", Bitwise)
VX_INSTR(ENTER, "enter", Bitwise)
VX_INSTR(JREL, "jrel", Bitwise)
VX_INSTR(JREL_JAE, "jrel.jae", Bitwise)
VX_INSTR(JREL_JB, "jrel.jb", Bitwise)
VX_INSTR(JREL_JCC, "jrel.jcc", Bitwise)
VX_INSTR(JREL_JCS, "jrel.jcs", Bitwise)
VX_INSTR(JREL_JE, "jrel.je", Bitwise)
VX_INSTR(JREL_JGE, "jrel.jge", Bitwise)
VX_INSTR(JREL_JGT, "jrel.jgt", Bitwise)
VX_INSTR(JREL_JHI, "jrel.jhi", Bitwise)
VX_INSTR(JREL_JLE, "jrel.jle", Bitwise)
VX_INSTR(JREL_JLS, "jrel.jls", Bitwise)
VX_INSTR(JREL_JLT, "jrel.jlt", Bitwise)
VX_INSTR(JREL_JMI, "jrel.jmi", Bitwise)
VX_INSTR(JREL_JNE, "jrel.jne", Bitwise)
VX_INSTR(JREL_JNZ, "jrel.jnz", Bitwise)
VX_INSTR(JREL_JPL, "jrel.jpl", Bitwise)
VX_INSTR(JREL_JVC, "jrel.jvc", Bitwise)
VX_INSTR(JREL_JVS, "jrel.jvs", Bitwise)
VX_INSTR(JREL_JZ, "jrel.jz", Bitwise)
VX_INSTR(LEAVE, "leave", Bitwise)
VX_INSTR(LOOP, "loop", Bitwise)
VX_INSTR(NOT, "not", Bitwise)
VX_INSTR(OR, "or", Bitwise)
VX_INSTR(SAR, "sar", Bitwise)
VX_INSTR(SHL, "shl", Bitwise)
VX_INSTR(SHR, "shr", Bitwise)
VX_INSTR(XOR, "xor", Bitwise)

/* --- Branch --- */
VX_INSTR(JMP, "jmp", Branch)
VX_INSTR(JMP_JAE, "jmp.jae", Branch)
VX_INSTR(JMP_JB, "jmp.jb", Branch)
VX_INSTR(JMP_JCC, "jmp.jcc", Branch)
VX_INSTR(JMP_JCS, "jmp.jcs", Branch)
VX_INSTR(JMP_JE, "jmp.je", Branch)
VX_INSTR(JMP_JGE, "jmp.jge", Branch)
VX_INSTR(JMP_JGT, "jmp.jgt", Branch)
VX_INSTR(JMP_JHI, "jmp.jhi", Branch)
VX_INSTR(JMP_JLE, "jmp.jle", Branch)
VX_INSTR(JMP_JLS, "jmp.jls", Branch)
VX_INSTR(JMP_JLT, "jmp.jlt", Branch)
VX_INSTR(JMP_JMI, "jmp.jmi", Branch)
VX_INSTR(JMP_JNE, "jmp.jne", Branch)
VX_INSTR(JMP_JNZ, "jmp.jnz", Branch)
VX_INSTR(JMP_JPL, "jmp.jpl", Branch)
VX_INSTR(JMP_JVC, "jmp.jvc", Branch)
VX_INSTR(JMP_JVS, "jmp.jvs", Branch)
VX_INSTR(JMP_JZ, "jmp.jz", Branch)
VX_INSTR(JMPR, "jmpr", Branch)
VX_INSTR(JUMPTABLE, "jumptable", Branch)
VX_INSTR(TYPESWITCH, "typeswitch", Branch)

/* --- Call --- */
VX_INSTR(CALLCLOSURE, "callclosure", Call)
VX_INSTR(CALLRAWCLOSURE, "callrawclosure", Call)
VX_INSTR(MKCLOSURE, "mkclosure", Call)
VX_INSTR(MKRAWCLOSURE, "mkrawclosure", Call)
VX_INSTR(TAILCALL, "tailcall", Call)

/* --- Compare --- */
VX_INSTR(CMPS, "cmps", Compare)
VX_INSTR(CMPU, "cmpu", Compare)

/* --- Concurrency --- */
VX_INSTR(AWAIT, "await", Concurrency)
VX_INSTR(EDM, "edm", Concurrency)
VX_INSTR(EDMW4, "edmw4", Concurrency)
VX_INSTR(EDMW6, "edmw6", Concurrency)
VX_INSTR(FULFILL, "fulfill", Concurrency)
VX_INSTR(FUTURE, "future", Concurrency)
VX_INSTR(GETFLDAT, "getfldat", Concurrency)
VX_INSTR(GETMETHAT, "getmethat", Concurrency)
VX_INSTR(GETPID, "getpid", Concurrency)
VX_INSTR(HLT, "hlt", Concurrency)
VX_INSTR(LOADMOD, "loadmod", Concurrency)
VX_INSTR(MONENTER, "monenter", Concurrency)
VX_INSTR(MONEXIT, "monexit", Concurrency)
VX_INSTR(MONNOTA, "monnota", Concurrency)
VX_INSTR(MONNOTI, "monnoti", Concurrency)
VX_INSTR(MONWAIT, "monwait", Concurrency)
VX_INSTR(PANIC, "panic", Concurrency)
VX_INSTR(REJECT, "reject", Concurrency)
VX_INSTR(RESUME, "resume", Concurrency)
VX_INSTR(SETMETHDBG, "setmethdbg", Concurrency)
VX_INSTR(SPAWN, "spawn", Concurrency)
VX_INSTR(SPAWNON, "spawnon", Concurrency)
VX_INSTR(SWAPCTX, "swapctx", Concurrency)
VX_INSTR(UNLOADMOD, "unloadmod", Concurrency)
VX_INSTR(YIELD, "yield", Concurrency)

/* --- Exception --- */
VX_INSTR(TRYENTER, "tryenter", Exception)
VX_INSTR(TRYLEAVE, "tryleave", Exception)

/* --- Float --- */
VX_INSTR(BITG2Z, "bitg2z", Float)
VX_INSTR(BITZ2G, "bitz2g", Float)
VX_INSTR(FABS, "fabs", Float)
VX_INSTR(FABS_PD, "fabs.pd", Float)
VX_INSTR(FABS_PS, "fabs.ps", Float)
VX_INSTR(FADD, "fadd", Float)
VX_INSTR(FADD_PD, "fadd.pd", Float)
VX_INSTR(FADD_PS, "fadd.ps", Float)
VX_INSTR(FCEIL, "fceil", Float)
VX_INSTR(FCEIL_PS, "fceil.ps", Float)
VX_INSTR(FCMP, "fcmp", Float)
VX_INSTR(FCMP_PD, "fcmp.pd", Float)
VX_INSTR(FCMP_PS, "fcmp.ps", Float)
VX_INSTR(FCVT, "fcvt", Float)
VX_INSTR(FCVT_PS, "fcvt.ps", Float)
VX_INSTR(FDIV, "fdiv", Float)
VX_INSTR(FDIV_PD, "fdiv.pd", Float)
VX_INSTR(FDIV_PS, "fdiv.ps", Float)
VX_INSTR(FEXTEND, "fextend", Float)
VX_INSTR(FFLOOR, "ffloor", Float)
VX_INSTR(FFLOOR_PS, "ffloor.ps", Float)
VX_INSTR(FLOAD, "fload", Float)
VX_INSTR(FMADD, "fmadd", Float)
VX_INSTR(FMADD_PS, "fmadd.ps", Float)
VX_INSTR(FMAX, "fmax", Float)
VX_INSTR(FMAX_PS, "fmax.ps", Float)
VX_INSTR(FMIN, "fmin", Float)
VX_INSTR(FMIN_PS, "fmin.ps", Float)
VX_INSTR(FMOV, "fmov", Float)
VX_INSTR(FMOWI, "fmowi", Float)
VX_INSTR(FMUL, "fmul", Float)
VX_INSTR(FMUL_PD, "fmul.pd", Float)
VX_INSTR(FMUL_PS, "fmul.ps", Float)
VX_INSTR(FNARROW, "fnarrow", Float)
VX_INSTR(FNEG, "fneg", Float)
VX_INSTR(FNEG_PD, "fneg.pd", Float)
VX_INSTR(FNEG_PS, "fneg.ps", Float)
VX_INSTR(FROUND, "fround", Float)
VX_INSTR(FROUND_PS, "fround.ps", Float)
VX_INSTR(FSQRT, "fsqrt", Float)
VX_INSTR(FSQRT_PD, "fsqrt.pd", Float)
VX_INSTR(FSQRT_PS, "fsqrt.ps", Float)
VX_INSTR(FSTORE, "fstore", Float)
VX_INSTR(FSUB, "fsub", Float)
VX_INSTR(FSUB_PD, "fsub.pd", Float)
VX_INSTR(FSUB_PS, "fsub.ps", Float)
VX_INSTR(FTRUNC, "ftrunc", Float)
VX_INSTR(FTRUNC_PS, "ftrunc.ps", Float)

/* --- Gc --- */
VX_INSTR(DEREF_WEAK, "deref_weak", Gc)
VX_INSTR(DROP, "drop", Gc)
VX_INSTR(FREE_WEAK, "free_weak", Gc)
VX_INSTR(GCALLOC, "gcalloc", Gc)
VX_INSTR(GCCOLLECT, "gccollect", Gc)
VX_INSTR(GCCONFIG, "gcconfig", Gc)
VX_INSTR(GCFINAL, "gcfinal", Gc)
VX_INSTR(GCFINALC, "gcfinalc", Gc)
VX_INSTR(GCRUN, "gcrun", Gc)
VX_INSTR(GCWB, "gcwb", Gc)
VX_INSTR(NEWOBJ, "newobj", Gc)
VX_INSTR(WEAKREF, "weakref", Gc)

/* --- Memory --- */
VX_INSTR(ADDCUR, "addcur", Memory)
VX_INSTR(ALLOC, "alloc", Memory)
VX_INSTR(ATOMICADD, "atomicadd", Memory)
VX_INSTR(ATOMICCAS, "atomiccas", Memory)
VX_INSTR(ATOMICLD, "atomicld", Memory)
VX_INSTR(ATOMICST, "atomicst", Memory)
VX_INSTR(CSEL, "csel", Memory)
VX_INSTR(FREE, "free", Memory)
VX_INSTR(GCDEMOTE, "gcdemote", Memory)
VX_INSTR(GCDEREF, "gcderef", Memory)
VX_INSTR(GCPROMOTE, "gcpromote", Memory)
VX_INSTR(MLD, "mld", Memory)
VX_INSTR(MOV, "mov", Memory)
VX_INSTR(MOVC, "movc", Memory)
VX_INSTR(MOVCH, "movch", Memory)
VX_INSTR(MOVH, "movh", Memory)
VX_INSTR(MST, "mst", Memory)
VX_INSTR(MVTAKE, "mvtake", Memory)
VX_INSTR(NEWOBJS, "newobjs", Memory)
VX_INSTR(READCUR, "readcur", Memory)
VX_INSTR(REALLOC, "realloc", Memory)
VX_INSTR(SHAREDSTAT, "sharedstat", Memory)
VX_INSTR(VCOPYH, "vcopyh", Memory)
VX_INSTR(VMCOPY, "vmcopy", Memory)
VX_INSTR(WRITECUR, "writecur", Memory)

/* --- Object --- */
VX_INSTR(ADDADVICE, "addadvice", Object)
VX_INSTR(CALLITF, "callitf", Object)
VX_INSTR(CALLM, "callm", Object)
VX_INSTR(CALLNI, "callni", Object)
VX_INSTR(CALLSUPER, "callsuper", Object)
VX_INSTR(CALLVIRT, "callvirt", Object)
VX_INSTR(CHECKCAST, "checkcast", Object)
VX_INSTR(CLASSATTRCOUNT, "classattrcount", Object)
VX_INSTR(CLASSATTRKEY, "classattrkey", Object)
VX_INSTR(CLASSATTRVAL, "classattrval", Object)
VX_INSTR(CLASSDOC, "classdoc", Object)
VX_INSTR(CLASSNAME, "classname", Object)
VX_INSTR(CMPJMP_JAE, "cmpjmp.jae", Object)
VX_INSTR(CMPJMP_JB, "cmpjmp.jb", Object)
VX_INSTR(CMPJMP_JCC, "cmpjmp.jcc", Object)
VX_INSTR(CMPJMP_JCS, "cmpjmp.jcs", Object)
VX_INSTR(CMPJMP_JE, "cmpjmp.je", Object)
VX_INSTR(CMPJMP_JGE, "cmpjmp.jge", Object)
VX_INSTR(CMPJMP_JGT, "cmpjmp.jgt", Object)
VX_INSTR(CMPJMP_JHI, "cmpjmp.jhi", Object)
VX_INSTR(CMPJMP_JLE, "cmpjmp.jle", Object)
VX_INSTR(CMPJMP_JLS, "cmpjmp.jls", Object)
VX_INSTR(CMPJMP_JLT, "cmpjmp.jlt", Object)
VX_INSTR(CMPJMP_JMI, "cmpjmp.jmi", Object)
VX_INSTR(CMPJMP_JNE, "cmpjmp.jne", Object)
VX_INSTR(CMPJMP_JNZ, "cmpjmp.jnz", Object)
VX_INSTR(CMPJMP_JPL, "cmpjmp.jpl", Object)
VX_INSTR(CMPJMP_JVC, "cmpjmp.jvc", Object)
VX_INSTR(CMPJMP_JVS, "cmpjmp.jvs", Object)
VX_INSTR(CMPJMP_JZ, "cmpjmp.jz", Object)
VX_INSTR(CMPJMPU_JAE, "cmpjmpu.jae", Object)
VX_INSTR(CMPJMPU_JB, "cmpjmpu.jb", Object)
VX_INSTR(CMPJMPU_JCC, "cmpjmpu.jcc", Object)
VX_INSTR(CMPJMPU_JCS, "cmpjmpu.jcs", Object)
VX_INSTR(CMPJMPU_JE, "cmpjmpu.je", Object)
VX_INSTR(CMPJMPU_JGE, "cmpjmpu.jge", Object)
VX_INSTR(CMPJMPU_JGT, "cmpjmpu.jgt", Object)
VX_INSTR(CMPJMPU_JHI, "cmpjmpu.jhi", Object)
VX_INSTR(CMPJMPU_JLE, "cmpjmpu.jle", Object)
VX_INSTR(CMPJMPU_JLS, "cmpjmpu.jls", Object)
VX_INSTR(CMPJMPU_JLT, "cmpjmpu.jlt", Object)
VX_INSTR(CMPJMPU_JMI, "cmpjmpu.jmi", Object)
VX_INSTR(CMPJMPU_JNE, "cmpjmpu.jne", Object)
VX_INSTR(CMPJMPU_JNZ, "cmpjmpu.jnz", Object)
VX_INSTR(CMPJMPU_JPL, "cmpjmpu.jpl", Object)
VX_INSTR(CMPJMPU_JVC, "cmpjmpu.jvc", Object)
VX_INSTR(CMPJMPU_JVS, "cmpjmpu.jvs", Object)
VX_INSTR(CMPJMPU_JZ, "cmpjmpu.jz", Object)
VX_INSTR(DECJNZ, "decjnz", Object)
VX_INSTR(DEFCLASS, "defclass", Object)
VX_INSTR(DEFFIELD, "deffield", Object)
VX_INSTR(DEFMETHOD, "defmethod", Object)
VX_INSTR(DLOPEN, "dlopen", Object)
VX_INSTR(DLSYM, "dlsym", Object)
VX_INSTR(FASTPOP, "fastpop", Object)
VX_INSTR(FASTPUSH, "fastpush", Object)
VX_INSTR(FIELDATTRCOUNT, "fieldattrcount", Object)
VX_INSTR(FIELDATTRKEY, "fieldattrkey", Object)
VX_INSTR(FIELDATTRVAL, "fieldattrval", Object)
VX_INSTR(FIELDCOUNT, "fieldcount", Object)
VX_INSTR(FIELDDOC, "fielddoc", Object)
VX_INSTR(FIELDNAME, "fieldname", Object)
VX_INSTR(FINDCLASS, "findclass", Object)
VX_INSTR(FINDFIELD, "findfield", Object)
VX_INSTR(FINDMETHOD, "findmethod", Object)
VX_INSTR(FULFILLHLT, "fulfillhlt", Object)
VX_INSTR(GCALLOCP, "gcallocp", Object)
VX_INSTR(GCFINALL, "gcfinall", Object)
VX_INSTR(GETCLASS, "getclass", Object)
VX_INSTR(GETFIELD, "getfield", Object)
VX_INSTR(GETMETHOD, "getmethod", Object)
VX_INSTR(GETSTATIC, "getstatic", Object)
VX_INSTR(INSTANCEOF, "instanceof", Object)
VX_INSTR(METHODATTRCOUNT, "methodattrcount", Object)
VX_INSTR(METHODATTRKEY, "methodattrkey", Object)
VX_INSTR(METHODATTRVAL, "methodattrval", Object)
VX_INSTR(METHODCOUNT, "methodcount", Object)
VX_INSTR(METHODDESC, "methoddesc", Object)
VX_INSTR(METHODDOC, "methoddoc", Object)
VX_INSTR(METHODNAME, "methodname", Object)
VX_INSTR(NEWOBJRAW, "newobjraw", Object)
VX_INSTR(PROCEED, "proceed", Object)
VX_INSTR(RETHROW, "rethrow", Object)
VX_INSTR(SETSTATIC, "setstatic", Object)
VX_INSTR(SPAWNARGS, "spawnargs", Object)
VX_INSTR(SPECIALIZE, "specialize", Object)
VX_INSTR(THROW, "throw", Object)

/* --- Other --- */
VX_INSTR(GCHANDLE, "gchandle", Other)
VX_INSTR(GETMGR, "getmgr", Other)
VX_INSTR(GETPROC, "getproc", Other)
VX_INSTR(GETVM, "getvm", Other)
VX_INSTR(HTRACK, "htrack", Other)
VX_INSTR(ISNULL, "isnull", Other)
VX_INSTR(LOADZ, "loadz", Other)
VX_INSTR(LOADZH, "loadzh", Other)
VX_INSTR(MEMSYNC, "memsync", Other)
VX_INSTR(MSGRECV, "msgrecv", Other)
VX_INSTR(MSGSEND, "msgsend", Other)
VX_INSTR(RSPAWN, "rspawn", Other)
VX_INSTR(SETCC, "setcc", Other)
VX_INSTR(SEXT, "sext", Other)
VX_INSTR(STRCAT, "strcat", Other)
VX_INSTR(STRCMP, "strcmp", Other)
VX_INSTR(STRCONV, "strconv", Other)
VX_INSTR(STRFINALIZE, "strfinalize", Other)
VX_INSTR(STRFLAT, "strflat", Other)
VX_INSTR(STRGETBYTES, "strgetbytes", Other)
VX_INSTR(STRGETENC, "strgetenc", Other)
VX_INSTR(STRGETKIND, "strgetkind", Other)
VX_INSTR(STRHASH, "strhash", Other)
VX_INSTR(STRINTERN, "strintern", Other)
VX_INSTR(STRLEN, "strlen", Other)
VX_INSTR(STRMAKE, "strmake", Other)
VX_INSTR(STRMAKE_H, "strmake_h", Other)
VX_INSTR(STRRAW, "strraw", Other)
VX_INSTR(STRRESERVE, "strreserve", Other)
VX_INSTR(STRSLICE, "strslice", Other)
VX_INSTR(UNWRAP, "unwrap", Other)

/* --- Stack --- */
VX_INSTR(ADDSP, "addsp", Stack)
VX_INSTR(POP, "pop", Stack)
VX_INSTR(PUSH, "push", Stack)
VX_INSTR(SUBSP, "subsp", Stack)
VX_INSTR(XCHG, "xchg", Stack)

/* --- System --- */
VX_INSTR(CALLNR, "callnr", System)
VX_INSTR(CALLVM, "callvm", System)
VX_INSTR(CALLVMR, "callvmr", System)
VX_INSTR(DEC, "dec", System)
VX_INSTR(GETARG, "getarg", System)
VX_INSTR(GETARGC, "getargc", System)
VX_INSTR(INC, "inc", System)
VX_INSTR(NOP1, "nop1", System)
VX_INSTR(NOP2, "nop2", System)
VX_INSTR(RET, "ret", System)
VX_INSTR(VMINFO, "vminfo", System)
VX_INSTR(VMINFOMANAGER, "vminfomanager", System)
/* clang-format on */
