name: CMake CI

on:
  push:
    branches: [ "develop", "release" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Update submodules explicitly
      run: git submodule update --init --recursive

    # DEPENDENCIAS WINDOWS
    - name: Install MinGW (Windows)
      if: matrix.os == 'windows-latest' && matrix.compiler == 'gcc'
      shell: powershell
      run: |
        choco install mingw -y
        $Env:PATH += ";C:\tools\mingw64\bin"

    # DEPENDENCIAS LINUX
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y libssl-dev clang

    # FIX LINE ENDINGS LINUX
    - name: Fix line endings (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install -y dos2unix
        find libs/SourceCode -type f -exec dos2unix {} \;

    # CONFIGURAR CMAKE
    - name: Configure CMake
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cmake -B build -G "MinGW Makefiles" -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S .
        else
          cmake -B build -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S .
        fi

    # BUILD
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    # TEST
    - name: Test
      working-directory: build
      run: ctest --output-on-failure